services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: group_class_backend
    ports:
      - "18000:18000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: group_class_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
