from enum import StrEnum


class ErrorCode(StrEnum):
    OK = "OK"
    VALIDATION_INVALID_ARGUMENT = "VALIDATION_INVALID_ARGUMENT"
    VALIDATION_REQUIRED_FIELD_MISSING = "VALIDATION_REQUIRED_FIELD_MISSING"
    CLASS_NOT_FOUND = "CLASS_NOT_FOUND"
    CLASS_VERSION_CONFLICT = "CLASS_VERSION_CONFLICT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    SYSTEM_INTERNAL_ERROR = "SYSTEM_INTERNAL_ERROR"
